[versions]
agp = "9.4.1"
kotlin = "2.4.20"
compose-bom = "2026.09.00"
activity-compose = "1.13.0"
lifecycle = "2.11.0"
libvlc = "3.7.6"
junit = "4.13.2"
ktlint-gradle = "14.2.0"
vlc-player-maven = "0.5.0"

[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-icons = { module = "androidx.compose.material:material-icons-extended" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
libvlc = { module = "org.videolan.android:libvlc-all", version.ref = "libvlc" }
junit = { module = "junit:junit", version.ref = "junit" }
vlc-player-maven = { module = "io.github.dooop:vlc-player", version.ref = "vlc-player-maven" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
